### ISSUE TITLE
Push data into database?

### ISSUE THREAD

**Issue by thequbit** [hhroc/traffairious#3]
Discuss if we want to push the data to a database rather than in flat files as to make advanced queries possible.  This will also make it easier to reuse the data in other projects/create visualizations.

**Comment by decause** [comment]
I think that we have all grown quite a bit since originally deploying this stack, and could make much more informed architecture decisions now. That being said, I'm still in the "keep it simple" camp, and like to use flat files when possible.

Closing this for now.

**Comment by thequbit** [comment]
For this particular app, I don't think that a database is needed.

**Comment by Nolski** [comment]
agreed.

**Comment by citruspi** [comment]
:+1:
